- python3.hcl
Python infers it automatically and correctly, and this also breaks
tools that use the system python2 interpreter as it points at a python3
installation.
> Don't explicitly set PYTHONHOME.

- jx.hcl
- kind.hcl
I'd missed the multi-arch support in packages; so lets add the ${arch} so that these packages can be used on arm as well
> fix: make jx and kind multi-arch

- aws-copilot.hcl
> AWS Copilot is an open source command line interface that makes it easy for developers to build, release, and operate production ready containerized applications on AWS App Runner, Amazon ECS, and AWS Fargate.
https://aws.github.io/copilot-cli/
https://github.com/aws/copilot-cli/releases
It's my first time contributing a package so would appreciate any feedback and tips!
> add aws copilot

- node.hcl
v16.4 fixed a segmentation fault I came up across. also trying to enable auto-version with a new "current" channel which matches [Node.js' verbiage](https://nodejs.org/en/).
> add current node version with auto-version

- README.md
Add Slack channel link to #cashapp at Gophers Slack to README.
> docs: Add Slack channel link

- python3.hcl
It seems that python 3.7 does not support ARM architectures. Also, as there is only 3.7.11 available as an AppImage, and 3.7.9 is the latest for OSX, this provides slightly differing versions for linux and OSX for `python-3.7`
> Python 3.7 for amd64 darwin and linux

- gojq.hcl
Add a package manifest for gojq (https://github.com/itchyny/gojq) - a
pure Go implementation of jq that also supports YAML for input and
output. It has a few other differences as documented in its README. It
can also be used as a library in your Go programs.
> Add package manifest for gojq

- protoc-gen-go-grpc.hcl
Add protoc-gen-go-grpc, another golang protoc plugin.
link: https://grpc.io/docs/languages/go/quickstart/
link: https://github.com/grpc/grpc-go/releases/tag/cmd/protoc-gen-go-grpc/v1.1.0
> Add protoc-gen-go-grpc

- protoc-gen-grpc-web.hcl
Add protoc-gen-grpc-web for grpc-web
https://github.com/grpc/grpc-web#grpc-web
https://grpc.io/docs/platforms/web/quickstart/
> add protoc-gen-grpc-web

- .github/workflows/ci.yml
The CI check for testing only changed packages manages to pick up
packages in unchanged files, as the `hermit search` command used does
not anchor the regex. Anchor it so we only find the versions of packages
in changed files.
> ci: Anchor "hermit search" pattern to exclude submatches

- helm.hcl
Adds the 3.6.1, 3.6.2, and 3.6.3 helm releases manually and sets up auto
versioning such that new releases will be automatically added.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Note: thanks for y'all's work on `hermit`! I wasn't sure the exact logic behind how auto-versioning is pulling new versions (specifically if it only takes into account versions after the latest present version in the config file). If there are any updates you would like me to make here I would be more than happy to do so. These patches include a security vulnerability fix that was not present in 3.6.0.
> Add helm 3.6 patches and setup auto versioning

- svu.hcl
This adds the semantic versioning utility tool which is used to automatically generate semantic versions based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
> feat(package): Add svu manifest

- flux.hcl
CLI for the flux Kubernetes framework https://fluxcd.io/
I tried to follow what was done for gotestsum (https://github.com/cashapp/hermit-packages/pull/69) but I didn't see any testing documentation so I haven't tested this locally.
I validated the source URL against the release format (https://github.com/fluxcd/flux2/releases/tag/v0.23.0).
> Add package for flux cli

- kustomize.hcl
CLI for the kustomize Kubernetes framework https://kustomize.io/
I tried to follow what was done for gotestsum (https://github.com/cashapp/hermit-packages/pull/69).
I validated the source URL against the release format (https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize/v4.4.1).
> Add package for kustomize cli

- dyff.hcl
CLI for the dyff tool https://github.com/homeport/dyff.
I tried to follow what was done for gotestsum (https://github.com/cashapp/hermit-packages/pull/69).
I validated the source URL against the release format (https://github.com/homeport/dyff/releases/tag/v1.4.6).
> Add package for dyff cli

- envoy.hcl
Upgrade envoy to v1.20.1 - this version should finally play nice again
with MacOS Monterey.
> Upgrade envoy to 1.20.1

- bazel.hcl
Note that this prompts the user for yes/no input because it leaves `platform "darwin" "arm64"` unsupported (not sure if this breaks automation). This is intentional as bazel only released binaries for it starting in 4.1.0, so we would need extra logic for versions < 4.1.0
> split up into bazel into platforms, add bazel 3.7.2

- svu.hcl
for svu v1.9 onwards seems like they started to pack all darwin binaries in `darwin_all` instead of `darwin_{arch}`.
This PR will fix this issue on versions since v1.9 
ref: https://github.com/caarlos0/svu/releases/
> fix: svu darwin release

- glab.hcl
Add package for [glab](https://github.com/profclems/glab/). Glab is to GitLab what [gh](https://github.com/cli/cli) is to GitHub.
> Add glab: gitlab command-line client

- terraform.hcl
Enable `auto-version` for terraform. Split the versions at pre-1.0.2 and
1.0.2+ as 1.0.2 is the first version with Darwin ARM64 binaries.
Link: https://releases.hashicorp.com/terraform
Link: https://github.com/hashicorp/terraform/releases
> terraform: Add auto-version

- step.hcl
step is an open-source command-line tool for developers, operators, and security professionals to configure and automate the smallstep toolchain and a swiss-army knife for day-to-day operations of open standard identity technologies.
> Add step CLI tool

- linkerd.hcl
Linkerd is an ultralight, security-first service mesh for Kubernetes. Linkerd adds critical security, observability, and reliability features to your Kubernetes stack with no code change required.
This PR adds the CLI tool for Linkerd stable releases.
> Add linkerd CLI tool

- rust.hcl
The Rust team defines different tiers of support for different platforms: https://doc.rust-lang.org/rustc/platform-support.html
* Tier 1 targets can be thought of as “guaranteed to work”. The Rust project builds official binary releases for each tier 1 target, and automated testing ensures that each tier 1 target builds and passes tests after each change.
* Tier 2 targets can be thought of as “guaranteed to build”. The Rust project builds official binary releases for each tier 2 target, and automated builds ensure that each tier 2 target builds after each change. Automated tests are not always run so it’s not guaranteed to produce a working build, but tier 2 targets often work to quite a good degree and patches are always welcome!
Unfortunately, for the rust hermit package, it uses the …
> fix: switch rust to use gnu instead of musl

- operator-sdk.hcl
Add a manifest for operator-sdk from v1.15.0 onwards. From v1.19.0,
darwin arm64 builds are released.
> Add operator-sdk v1.15.0+

- mockery.hcl
Checksums added into a new block to prevent auto-versioning from
applying these SHAs to future versions.
> mockery: Add asset checksums and test declaration

- python3.hcl
PYTHONHOME is probably no longer needed.
> No longer set PYTHONHOME

- mockery.hcl
Also fixes problem where commit 309eb8d7a2 created two "2.10.4"
versions.
> mockery: Add version 2.10.6

- azcopy.hcl
This is my first ever point of contact with Hermit, so I may not be following the best practices in terms of creating a solid manifest file. If there's anything terribly wrong, then please do let me know. Verified with:
```console
$ hermit test azcopy --trace --debug
info:validate: Validating azcopy-10.14.1
trace: HEAD https://azcopyvnext.azureedge.net/release20220315/azcopy_linux_amd64_10.14.1.tar.gz
trace: HEAD https://azcopyvnext.azureedge.net/release20220315/azcopy_darwin_amd64_10.14.1.zip
trace: HEAD https://azcopyvnext.azureedge.net/release20220315/azcopy_darwin_amd64_10.14.1.zip
info:validate: Validating azcopy@latest
trace: HEAD https://azcopyvnext.azureedge.net/release20220315/azcopy_linux_amd64_10.14.1.tar.gz
trace: HEAD …
```
> azcopy: add initial manifest

- sentry-cli.hcl
https://docs.sentry.io/cli/
seems they are using a mix of "arch" and "xarch" for darwin making this a bit more verbose https://github.com/getsentry/sentry-cli/releases
> sentry-cli: add initial manifest

- goproxy.hcl
this PR adds goproxy via 
```
hermit manifest create https://github.com/goproxy/goproxy/releases/download/v0.10.2/goproxy_0.10.2_linux_amd64.tar.gz > goproxy.hcl
```
> add goproxy

- cosign.hcl
`Cosign` is a sigstore tool for container signing, verification and
storage in an OCI registry.
Tested with the following commands on `linux-amd64` and `darwin-amd64`:
```bash
$ . bin/activate-hermit
$ for v in "1.0.0" "1.1.0" "1.2.0" "1.3.0" "1.4.0" "1.5.0" "1.6.0" "1.7.1" "1.8.0"; do hermit install cosign-$v; cosign version; done
```
> Add cosign to hermit-packages

- kubeseal.hcl
`kubeseal` encrypts your Secret into a SealedSecret, which is safe to store - even to a public repository. The SealedSecret can be decrypted only by the controller running in the target cluster and nobody else.
> Add kubeseal

- cfssl.hcl
Add cfssl manifest - Cloudflare's PKI and TLS toolkit. No arm releases.
> Add cfssl manifest

- helm-docs.hcl
`helm-docs` is a tool for auto-generates documentation from helm charts into markdown file. 
This is tested on `Darwin` amd64 machines
> add helm-docs

- rustup.hcl
This *should* replace the `rustup-init` package.
But, I've left `rustup-init` in case anyone depends on it. It's terrible though.
> Add rustup

- github-comment.hcl
Adds `github-comment` to be managed by Hermit: https://suzuki-shunsuke.github.io/github-comment/
> Add GitHub Comment

- rustup.hcl
This doesn't work reliably as `on install` doesn't trigger after a `git clone` + `hermit-activate` sequence.
> rustup: remove rustup auto-install

- dotnet.hcl
This diff hardcodes latest release's download urls. 
Adding new releases requires running a script (it is far too annoying otherwise)
> feat: add dotnet

- mysqladmin.hcl
This is separate from mysql-client because the linux deb packages are different, and also probably not everybody who wants mysql-client will want mysqladmin anyway.
> feat: Add a mysqladmin package

- rust.hcl
Rust source url should contain ${xarch} as a parameter, rather than being hardcoded to x86_64
> Rust linux source url should include ${xarch}

- python3.hcl
Python3 on linux arm64 has no pgo, so a a different source url is required
> Python3 on linux arm64 doesn't support pgo => needs a different source url

- .github/workflows/autoversion.yml
There is no good way of testing this, so it will just have to wait until the next run. Not a big deal.
> fix: test changed packages when auto-versioning

- corretto.hcl
Changelog:
https://github.com/corretto/corretto-11/blob/develop/CHANGELOG.md#corretto-version-1101781.
> Add Corretto 11.0.17.8.1 JDK distribution.

- azcopy.hcl
It's not at all obvious from the repository and someone would have to go through the trouble of figuring this out if they wanted to add a new version to the manifest instead of me.
> docs(azcopy.hcl): add comments explaining how to find out latest version/date

- kscript.hcl
Conflicts with internal private definitions of openjre, when used with an internal private hermit-packages repo.
> Remove runtime dep, which conflicts in cases of private packages repos.

- python3.hcl
This PR makes a symlink for pip > pip3 and python > python3 since some packages expect to find python instead of python3.
> Add pip/python to python3

- tinygo.hcl
Only install the tinygo binary and not wasm-opt as wasm-opt is also in
the dependency package `binaryen`. On Linux, the tinygo release contains
`wasm-opt` but Mac/Darwin does not, which is why this probably not
noticed before.
> tar tvf tinygo0.25.0.linux-amd64.tar.gz | grep /bin/
drwxr-xr-x root/root         0 2022-08-03 06:04 tinygo/bin/
-rwxr-xr-x root/root  17360056 2022-08-03 06:02 tinygo/bin/wasm-opt
-rwxr-xr-x root/root 138802272 2022-08-03 06:04 tinygo/bin/tinygo
> tar tvf tinygo0.25.0.darwin-amd64.tar.gz | grep /bin/
drwxr-xr-x runner/staff      0 2022-08-03 05:53 tinygo/bin/
-rwxr-xr-x runner/staff 115737032 2022-08-03 05:51 tinygo/bin/tinygo
Trying to install tinygo on Linux gives the following:
> hermit install tinygo
info:tinygo-0.26.0:install: Installing tinygo-0.26.0 …
> tinygo: Don't install wasm-opt binary

- openjdk.hcl
Released upstream by OpenJDK on 2022-10-18 [0], with the Eclipse Temurin builds made available on 2022-10-26 [1].
This fixes 5 medium-to-low-severity  CVEs reported against OpenJDK 17.0.4 and earlier [2], which fixed one high-severity and several medium-to-low-severity CVEs against 17.0.3 and earlier [3], which fixed two high-severity and several medium-to-low severity CVEs against 17.0.2 and earlier [4].
[0]: https://mail.openjdk.org/pipermail/jdk-updates-dev/2022-October/018120.html
[1]: https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.5%2B8
[2]: https://openjdk.org/groups/vulnerability/advisories/2022-10-18
[3]: https://openjdk.org/groups/vulnerability/advisories/2022-07-19
[4]: https://openjdk.org/groups/vulnerability/advisories/2022-04-19
> Add openjdk 17.0.5+8

- mage.hcl
See https://github.com/cashapp/hermit/issues/195
> Remove go requirement from mage as it forces a go upgrade

- gradle.hcl
SHA256 sum taken from https://services.gradle.org/distributions/gradle-7.6-bin.zip.sha256
> chore: add gradle 7.6

- node.hcl
This will make sure cache files are stored under `.hermit` folder, similar to what other toolchains like Rust is doing.
Feedback/suggestions welcomed.
> Set NPM_CONFIG_PREFIX in node.hcl

- python3.hcl
This will make sure cache files are stored under `.hermit` folder, similar to what other toolchains like Rust is doing.
Feedback/suggestions welcomed.
> Set PIP_CACHE_DIR in python3.hcl

- just.hcl
This PR adds newer releases for `just` and also adds the `auto-release` directive which I've seen in other packages but not `just` (does `just` predate `auto-release` or is there a reason for that?).
> Update just package

- just.hcl
I made a mistake in #262, the commas make `just` not installable now. `hermit test just` passes with this change.
> Remove commas in just.hcl

- tekton-cli.hcl
This commit adds the [Tekton CLI tool][0] to interact with [Tekton Pipelines][1].
[0]: https://github.com/tektoncd/cli
[1]: https://tekton.dev/
> Add Tekton CLI

- podman.hcl
The [authversion jobs](https://github.com/cashapp/hermit-packages/actions/workflows/autoversion.yml) have been failing for the last ~week. Here is an example failure:
```
fatal: app/auto_version_cmd.go:30: manifest/digest/digest.go:89: failed to compute digest for podman-4.4.0/linux-amd64: manifest/digest/digest.go:161: state/state.go:324: cache/cache.go:149: https://github.com/containers/podman/releases/download/v4.4.0/podman-remote-static.tar.gz: cache/http.go:88: download failed: 404 Not Found (404)
```
https://github.com/cashapp/hermit-packages/actions/runs/4120270815/jobs/7114826978
I traced the issue back to a change in the artifact names that are uploaded with podman: https://github.com/containers/podman/pull/16667
I think this change to the manifest will fix it.
I tested this …
> fix: podman linux path rename

- kotlin.hcl
In some hermit CI environments, some tools require KOTLIN_HOME and can't infer it.
> Add a KOTLIN_HOME env var

- kotlin.hcl
Reverts cashapp/hermit-packages#289
This broke some CI situations.
> Revert "Add a KOTLIN_HOME env var"

- fd.hcl
- git-cliff.hcl
- gotestfmt.hcl
- lefthook.hcl
- loki-logcli.hcl
- loki-promtail.hcl
should fix these warnings
```
warn: could not auto-version "/home/runner/work/hermit-packages/hermit-packages/fd.hcl": 14:1: https://api.github.com/repos/skarkdp/fd/releases/latest: GitHub API request failed with 404 Not Found
warn: could not auto-version "/home/runner/work/hermit-packages/hermit-packages/git-cliff.hcl": 38:1: https://api.github.com/repos/git-cliff/git-cliff/releases/latest: GitHub API request failed with 404 Not Found
warn: could not auto-version "/home/runner/work/hermit-packages/hermit-packages/gotestfmt.hcl": 6:1: https://api.github.com/repos//GoTestTools/gotestfmt/releases/latest: GitHub API request failed with 404 Not Found
warn: could not auto-version "/home/runner/work/hermit-packages/hermit-packages/hlb.hcl": 13:1: …
```
> fix: auto-versioning woes

- openjdk.hcl
Released upstream by OpenJDK on 2023-01-17 [0], with the Eclipse Temurin builds made available on 2023-01-19 [1]. This fixes two CVEs reported against OpenJDK 17.0.5 and earlier [2].
[0]: https://mail.openjdk.org/pipermail/jdk-updates-dev/2023-January/020196.html
[1]: https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.6%2B10
[2]: https://openjdk.org/groups/vulnerability/advisories/2023-01-17
> Add openjdk 17.0.6+10

- trh.hcl
- tuc.hcl
Thistle Release Helper (trh) is a tool to help prepare releases for
device OTA updates. https://docs.thistle.tech/release_helper/overview
Thistle Update Client (tuc) is an application running on a device to
take care of OTA updates.
https://docs.thistle.tech/update_client/overview
We also add sha256 digests of trh and tuc binaries, in the second commit.
> Add packages trh and tuc

- goss.hcl
I discovered two bugs (🐛) when I was testing this out.
1. I had accidentally add the `.exe` suffix to the `darwin` platform.
2. I expected `on "unpack" { ... }` in `darwin` to override the base level `on "unpack" { ... }` but it did not.
I missed these in my initial tests because I tested the code, made some updates, and then skipped re-testing. I re-tested after the changes this time.
```
> hermit install goss --trace
info:goss-0.3.21:install: Installing goss-0.3.21
debug:goss-0.3.21:install: From https://github.com/goss-org/goss/releases/download/v0.3.21/goss-alpha-darwin-amd64
debug:goss-0.3.21:install: To /Users/dolan/Library/Caches/hermit/pkg/goss-0.3.21
debug:goss-0.3.21:link: Linking binaries for goss-0.3.21
debug:goss-0.3.21:link: ln -s "hermit" …
```
> fix: `goss.hcl` two bugs

- go.hcl
**Summary**
[go.hcl](https://github.com/cashapp/hermit-packages/blob/master/go.hcl) only updated the latest minor version, and ignored the previous minors whenever a new minor version was published. e.g., 1.**19**.5 was not updated to 1.**19**.6 when 1.**20** was released.
This handles the issue by splitting each minor into its own auto-update logic by updating the XPath query to only collect the relevant version, as seen in [node.hcl](https://github.com/cashapp/hermit-packages/blob/master/node.hcl).
> Golang minor version support

- flink.hcl
The dlcdn links only work for the latest patch release, and don't contain all historical versions. For easier copypasta let's convert all the links to the archive links which have historical versions.
> Add more flink versions

- botb.hcl
Tested locally by calling `hermit install botb && botb`:
```bash
> hermit install botb && botb
info:botb-1.8.0:install: Installing botb-1.8.0
[+] Break Out The Box
[+] Finished                                        
```
> feat: 📦 add botb manifest

- sqlc.hcl
see: https://github.com/kyleconroy/sqlc/issues/2124
> fix: update sqlc's linux binary hash due to binary redistribution

- .github/workflows/autoversion.yml
HashiCorp has been republishing binaries for their tools every few months, and each time that happens the Hermit packages for those tools break due to the digests in the Hermit packages no longer matching the binaries downloaded from HashiCorp's releases website, so users of those Hermit packages see an error like:
```
fatal:hermit: https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_darwin_amd64.zip: https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_darwin_amd64.zip: checksum 685258b525eae94fb0b406faf661aa056d31666256bf28e625365a251cb89fdc should have been 26afa7cda355fbf32a2b4cfd9122a49132f1b68337691b91f05caa0b1023c388
```
Each time this has happened in the past we have had to update the checksums in the Hermit package manifests for those HashiCorp tools, for …
> Auto-refresh HashiCorp package checksums daily

- trh.hcl
- tuc.hcl
Starting at version 0.1.11, there's a change in the URL patterns for `trh` and `tuc` artifacts. We adjusted the package manifests to describe both the old and new patterns.
Also run `hermit manifest add-digests tuc.hcl trh.hcl` to add sha256 sums.
> Add trh/tuc 0.1.11, 0.1.12

- .github/workflows/autoversion.yml
Reverts cashapp/hermit-packages#319
Unfortunately this failed auto-versioning, so I've reverted it: https://github.com/cashapp/hermit-packages/actions/runs/4776022152
> Revert "Auto-refresh HashiCorp package checksums daily"

- openjdk.hcl
Released upstream by OpenJDK on 2023-04-18 [0], with the Eclipse Temurin builds made available on 2023-04-19 [1]. This fixes seven CVEs reported against OpenJDK 17.0.6 and earlier [2].
[0]: https://mail.openjdk.org/pipermail/jdk-updates-dev/2023-April/021899.html
[1]: https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.7%2B7
[2]: https://openjdk.org/groups/vulnerability/advisories/2023-04-18
> Add openjdk 17.0.7+7

- openjdk.hcl
This build seems to work better, having a build for m1 arch.
Good for older systems still using JDK 8 but using m1 macs.
> Adds zulu8.70.0.23 for support for m1 macs working in java 1.8.

- protoc-gen-go.hcl
prebuilt binaries are available as of https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.28.1
> fix: enable arm64 for protoc-gen-go

- openjdk.hcl
Released upstream by OpenJDK on 2023-07-18 [0], with the Eclipse Temurin builds made available on 2023-07-20 [1]. This fixes seven CVEs reported against OpenJDK 17.0.7 and earlier [2].
[0]: https://openjdk.org/groups/vulnerability/advisories/2023-07-18
[1]: https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.8%2B7
[2]: https://mail.openjdk.org/pipermail/jdk-updates-dev/2023-July/024063.html
> Add openjdk 17.0.8+7

- flink.hcl
According to Apache Downloads (https://www.apache.org/dyn/closer.cgi):
> We suggest the following site for your download:
>
> https://dlcdn.apache.org/
It is my understanding that the archive was previously used and kept for historical reasons.
> chore: add versions `1.15.4`, `1.16.2`, & `1.17.1` for flink using the new dlcnd sub-domain.

- codecov.hcl
Adds version 0.6.2 of the codecov uploader since codecov support indicated we're running into bugs since we're using an old uploader version in this ticket: https://codecoventerprise.codecov.io/hc/en-us/requests/102089
where CodeCov is counting comments as part of it's code quality inspections
> Adds version 0.6.2 of the codecov uploader

- kubectl.hcl
Included newer versions to kubectl package to keep up with server side versions of k8s. Right now the repo only goes to 1.24 and k8s is already on 1.28. This will add a lot of value to people actively working on k8s environments since it will allow them to leverage hermit to test new k8s features that have been released after 1.24.
> feat: Upgrade `kubectl` binaries

- cfssljson.hcl
Adding the package configuration to install `cfssljson` because I didn't see a way to bundle it together with `cfssl`. Just included the same versions that are managed in the current `cfssl` package to keep both binaries in sync because at the end of the day they are compiled together in the [cfssl repo](https://github.com/cloudflare/cfssl).
> feat: Adds `cfssljson` package

- node.hcl
npx will fail to execute any package unless .hermit/node/lib exists. Create this folder on install or activation.
Although this should be fixed upstream in `npx` itself, it's still valuable to have a working `npx`.
Fixes: #309
> fix: npx fails to run

- podman.hcl
podman linux releases now have a bin/ folder
Avoid using strip = 1 to guard against the ./bin/podman case which requires strip = 2
> fix(podman): fail to unpack and invalid checksums

- bitwarden-secrets-cli.hcl
This adds the bitwarden-secrets-cli which is used to interface to the new Bitwarden secrets manager from a CLI.
> feat: Add bitwarden secrets CLI

- helmfile.hcl
This adds a package definition for the tool `helmfile` which is used to declaratively manage helm repositories. See https://helmfile.readthedocs.io/en/latest/ for more information about the tool specifics.
> feat: Add helmfile

- gcrane.hcl
The `crane` implementation actually consists of the `gcrane` executable as well as the `crane` executable.  Thus, this is a copy of the `crane` implementation just with `gcrane` used as the output executable (couldn't tell if multiple executables could be the result of a package installation).
> Add Gcrane

- envtpl.hcl
- k8split.hcl
Package `envtpl` and `k8split`, fetching from hermit-build (see https://github.com/cashapp/hermit-build/pull/14)
> Add envtpl and k8split

- errtrace.hcl
The auto-version for errtrace references another project
instead of itself.
> fix(errtrace): Fix auto-version section

- az-speechsdk.hcl
this has been a pretty tricky dependency, the packaging is different for mac and linux as well as the correct cgo flags. this _should_ work now - confirm that it unpacks correctly and the env flags are set correctly on mac and linux.
> fix: azure speech

- atlas.hcl
running hermit atlas on m1 mac gives error `fatal:hermit: fork/exec /Users/hua/Library/Caches/hermit/pkg/atlas-0.15.0/atlas: bad CPU type in executable`
the newest version adds m1 binaries. this PR supports that moving forward.
test plan: ran `hermit manifest add-digests atlas.hcl` and `hermit test atlas`
> chore: atlas: include arm64 binary for mac

- nsc.hcl
This adds a manifest for `nsc` which is the client for Namespace.so which provides hosted GitHub Actions and Buildkite Workers. 
For more details see https://namespace.so/docs/getting-started/installation
@nichtverstehen any interest in referencing Hermit in the install docs?
> Add a manifest for nsc client for namespace.so

- nsc.hcl
I missed that there was an additional binary to be installed next to the `nsc` binary in https://github.com/cashapp/hermit-packages/pull/429. 
This adds it!
> Install docker-credential-nsc in the nsc manifest

- ffprobe.hcl
ffprobe is a companion binary to ffmpeg and they are released together. I considered whether to add this to the ffmpeg manifest, but they end up quite large statically linked binaries and it's nice to be able to choose which you install.
> Add a manifest for ffprobe (part of ffmpeg)

- actionlint.hcl
Add actionlint package, because waiting for GitHub workflow runs is too cumbersome an the hermit package `action-validator` didn't work.
cc @camh-
> Add actionlint package

- mysql-client.hcl
- mysqladmin.hcl
These versions use a multirelease tarball for ubuntu, and select the appropriate binary inside the tarball on unpack. This is needed to work around libssl dynamic library dependencies that differ on the two versions of Ubuntu.
> Add mysql-client and mysqladmin 8.0.36 versions

- mkcert.hcl
I would like to add mkcert as I use it pretty often for local k8s development. 
https://mkcert.dev
https://github.com/FiloSottile/mkcert
Thanks
> Adds mkcert

- micromamba.hcl
micromamba environment variable fix. vars must be expanded (rather than reference each other)
> micromamba env fix

- git-absorb.hcl
Adds [git absorb](https://github.com/tummychow/git-absorb) tool. Tested on MacOS 14.3 and Ubuntu 22.04.
> Add git absorb

- arm-gnu-toolchain-xpack.hcl
Updates `arm-gnu-toolchain` to add `10.3-2021.10` and `11.3.rel1` [releases](https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads). Official ARM releases are split across [two](https://developer.arm.com/downloads/-/gnu-rm) [sites](https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads) now, so comments have been added explaining which release site the versions come from.
Also added is an alternative arm toolchain provider `arm-gnu-toolchain-xpack`. The [xPack releases](https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases) have some benefits such as `arm-none-eabi-gdb-py3`, native `darwin-aarch64` builds and consistent semver and arch/os release naming.
> arm: updates arm-gnu-toolchain and adds xpack alternative

- gitversion
A handy semversioning tool. https://gitversion.net/docs/
Adding the stable version as well as the latest beta version for grabs.
> Add GitTools/Gitversion for semversioning

- cargo-nextest.hcl
Adds cargo-nextest for faster Rust testing: https://nexte.st/book/how-it-works.html
> Added cargo-nextest

- clang-dev.hcl
Adds `clang-dev` package for [llvmbox-dev](https://github.com/rsms/llvmbox/releases).
This is needed if you want to build with `clang` on MacOS, otherwise some libraries like `libxml` won't be found.
> Add clang-dev package

- dart.hcl
- adds latest dart v3.3.3 by following https://github.com/cashapp/hermit-packages/pull/356
- download urls and sha-256 sums from https://dart.dev/get-dart/archive
- verified correctness locally with `testing` attribute as described in the spec: https://cashapp.github.io/hermit/packaging/tutorial/#testing-the-package
> feat: add dart sdk v3.3.3

- pkl.hcl
I was wondering, why version digests have not been added since the last updates. Fixed the source URL now.
> FIX: missing version variable in pkl.hcl

- bitwarden-secrets-cli.hcl
The `bitwarden-secrets-cli` package was giving the following warnings:
```text
warn: invalid manifest reference bitwarden-secrets-cli-0.3.0 in bitwarden-secrets-cli.hcl: unknown variable $arch_
warn: invalid manifest reference bitwarden-secrets-cli@latest in bitwarden-secrets-cli.hcl: unknown variable $arch_
warn: invalid manifest reference bitwarden-secrets-cli@0 in bitwarden-secrets-cli.hcl: unknown variable $arch_
warn: invalid manifest reference bitwarden-secrets-cli@0.3 in bitwarden-secrets-cli.hcl: unknown variable $arch_
```
This PR fixes the error and updates the manifest with the latest version of `bws`.
`hermit manifest auto-version` dropped the windows versions for some reason, I'm not sure why that happened.
> Fix arch syntax in bitwarden-secrets-cli package

- dfu-util.hcl
Adds the `dfu-util` tool which is useful for updating/flashing Arduino, STM32 and other embedded targets using their built-in USB bootloader.
> Add dfu-util package

- release-cli.hcl
This PR add gitlab's release-cli tool: https://gitlab.com/gitlab-org/release-cli/-/blob/master/README.md?ref_type=heads
> Gitlab release-cli tool

- temporal-cli.hcl
Temporal has a new CLI available (separate from the already available `tctl`), one that includes a lot more functionality including the ability to run a local dev Temporal server. This PR adds this tool to Hermit via its latest github release.
> Add new Temporal CLI to Hermit

- yq.hcl
`yq` has released `arm64` binaries since `4.9.6`. Update `yq`'s darwin configuration to support this.
> Support darwin-arm64 binaries for yq

- cargo-cross.hcl
Adds [cargo cross](https://github.com/cross-rs/cross), a tool used to simplify cross compiling for cargo projects.
> Add cargo-cross

- clang-tidy.hcl
This adds [clang-tidy](https://clang.llvm.org/extra/clang-tidy/). The `hcl` is mostly a copy of [clang-format.hcl](https://github.com/cashapp/hermit-packages/blob/master/clang-format.hcl) as both packages come from the same repo.
> Add clang-tidy

- gradle.hcl
https://docs.gradle.org/8.8/release-notes.html
[checksum](https://gradle.org/release-checksums/) matches locally:
``` bash
$ curl -sSL https://services.gradle.org/distributions/gradle-8.8-bin.zip | sha256sum
a4b4158601f8636cdeeab09bd76afb640030bb5b144aafe261a5e8af027dc612
```
> Gradle 8.8

- parse-changelog.hcl
parse-changelog is a tool to parse changelog files
and extract sections of them in a scriptable way.
It provides JSON or plain text output which can be fed into other tools.
For example, it can fill in release notes for goreleaser
instead of using commit messages.
goreleaser release \
--release-notes <(parse-changelog CHANGELOG.md $VERSION)
> Add taiki-e/parse-changelog

- maestro.hcl
Maestro is a tool to run mobile UI tests.
https://maestro.mobile.dev/
Resolves https://github.com/cashapp/hermit-packages/issues/407
> Add Maestro CLI package

- openjdk.hcl
Adding openjdk 21 to the public sources for hermit
> chore: add openjdk 21 to sources

- sqlite.hcl
Had to introduce a `cpu` variable cause it looks like they switched to `x64`
> Update sqlite.hcl to version 3.46.1

- sqlite.hcl
In 3.46.1 version of `sqlite` packaging no longer stores the binaries under a directory, so we get the following error
```yaml
failed to find binaries "/Users/redacted/Library/Caches/hermit/pkg/sqlite-3.46.1/*"
```
```yaml
info:sqlite-3.46.1:install: Installing sqlite-3.46.1
debug:sqlite-3.46.1:install: From https://www.sqlite.org/2024/sqlite-tools-osx-x64-3460100.zip
debug:sqlite-3.46.1:install: To /Users/redacted/Library/Caches/hermit/pkg/sqlite-3.46.1
trace:sqlite-3.46.1: timeout for acquiring the lock is 30s
trace:sqlite-3.46.1: cachePath /Users/redacted/Library/Caches/hermit/cache/2d/2d6fbcc91d554ac9800d94cdc687014c3b885b717fad554c4f0161c069ea918c-sqlite-tools-osx-x64-3460100.zip checksum  url https://www.sqlite.org/2024/sqlite-tools-osx-x64-3460100.zip
trace: GET …
```
> fix: update path prefix for sqlite binaries

- uv.hcl
`uv` includes the `uvx` binary now
> uv.hcl: include all binaries with `"*"`

- awscli.hcl
awscli's releases tab is empty now for some reason, the auto version doesn't work as expected, added the latest one for now
> fix: add awscli 2.17.51

- k9s.hcl
this is always installing v0.27.0
```sh
hermit install k9s-0.32.5
k9s version
____  __.________
|    |/ _/   __   \______
|      < \____    /  ___/
|    |  \   /    /\___ \
|____|__ \ /____//____  >
\/            \/
Version:    v0.27.0
Commit:     b5a7cfb3af43a0a79423683094bd33b1b9605faf
Date:       2023-01-26T18:09:55Z
```
> [k9s] fix source version

- kubebuilder.hcl
When installing `kubebuilder` it looks like there's an issue with an `envtest` dependency, but `kubebuilder` provides a way to manage the resource itself. Since how `envtest` is managed is tied in closely with `kubebuilder` it felt right to manage that resource with `kubebuilder` config rather than in Hermit, but open to handling this a different way!
> fix(kubebuilder): remove envtest from requires

- kubectl-argo-rollouts.hcl
kubectl-argo-rollouts plugin allows you to manage and visualise the argo rollout and can be used as a plugin together with kubectl. 
https://argo-rollouts.readthedocs.io/en/stable/installation/
> feat:add kubectl argo rollouts cli

- android-cmdline-tools.hcl
- corretto.hcl
tested working with `openjdk-21.0.3_9`. corresponding JDK version wasn't added with corretto, added that too.
> feat: add android cmdline-tools, add corretto@21

- kotlin.hcl
The 2.1.0 release doesn't have bin/kotlin-dce-js and so the package fails to install. It's broken so removing it seems like the right fix for the short term.
> Remove kotlin 2.1.0 and disable auto-versioner

- kotlin.hcl
- Re-enable Kotlin bumps
- Add version 2.1.0
- Ignore the now missing `kotlin-dce-js` binary going forward
> kotlin-2.1.0

- civo.hcl
- myks.hcl
Sorry, missed this during my initial PR adding myks.
Also: can you tell me how I kick of the auto-versioning? The nightly run didn't fetch all the versions for some reasons.
And when I am running `hermit -d manifest auto-version --update-digests civo.hcl` or `hermit -d manifest auto-version --update-digests myks.hcl` locally they also don't update the files and the output is `debug: Auto-versioning /<path-to-repo>/hermit-packages/<package-name>.hcl`. 
I can't find anything in the documentation to help me here. Help would be greatly appreciated :) 
Thanks
> Add Digests for CiVo and Myks

- docker-cli.hcl
The Docker CLI binaries on https://download.docker.com/*/static/stable/* has changes so their checksums too.
```shell
curl -sSLo docker-linux-x86_64-27.5.0.tgz https://download.docker.com/linux/static/stable/x86_64/docker-27.5.0.tgz
curl -sSLo docker-mac-aarch64-27.5.0.tgz https://download.docker.com/mac/static/stable/aarch64/docker-27.5.0.tgz
curl -sSLo docker-mac-x86_64-27.5.0.tgz https://download.docker.com/mac/static/stable/x86_64/docker-27.5.0.tgz
sha256sum docker-linux-x86_64-27.5.0.tgz
sha256sum docker-mac-aarch64-27.5.0.tgz
sha256sum docker-mac-x86_64-27.5.0.tgz
```
```
4fca6bb9a3f4e13c50dea35aeef57aad735aed8e7eff67ef3741f777ce2c2eb7  docker-linux-x86_64-27.5.0.tgz
268d04a2622579a611fc873e44b49de2ee3e0f0ad874b712160300fb60b9aba7  docker-mac-aarch64-27.5.0.tgz …
```
> fix: update Docker cli checksums

- .github/workflows/autoversion.yml
- ftl.hcl
If auto-versioning is rate limited, shuffling the packages should at least make sure that subsequent runs will eventually work on all packages.
> fix: hack for rate limiting

- doppler.hcl
This pull request includes several changes to the `doppler.hcl` file to enhance the configuration for the Doppler CLI. The changes primarily focus on defining the CLI description, specifying binaries, setting up platform-specific variables, and providing versioning and checksum information.
Key changes include:
* Added a description and specified binaries for the Doppler CLI.
* Configured platform-specific variables for `darwin` and `linux` platforms.
* Defined the source URL template for downloading the Doppler CLI release.
* Added versioning information with auto-versioning based on GitHub releases.
* Provided SHA256 checksums for different platform-specific artefacts.
> feat: add doppler cli

- kubectl.hcl
Add versions for the recent minor versions of `kubectl`; [see upstream releases](https://kubernetes.io/releases/).
> kubectl: add versions 1.30, 1.31, 1.32

- jfrog-cli.hcl
This commit adds the [Jfrog CLI tool](https://github.com/jfrog/jfrog-cli) to interract with [JFrog products](https://jfrog.com).
> Add Jfrog CLI

- git-changelog-command-line.hcl
- git-changelog-command-line/git-changelog-command-line.sh
git-changelog-command-line is a command line front-end for git-changelog-lib that can be used to generate changelogs based on git history.
There is no appropriate subcommand to use for a `test`.
> feat: add git-changelog-command-line

- hadolint.hcl
use xarch (resolves to x86_64) var instead of arch (resolves to amd64)
error message:
`fatal:hermit: https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-linux-amd64: download failed: 404 Not Found (404), source url: https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-linux-amd64`
> fix[hadolint]: use xarch var instead of arch

- fd.hcl
Change the hardcoded `x86_64` to `${xarch}` so we can get appropriate
binaries on arm64, but leave `x86_64` hardcoded for the releases older
than 10.1.0 as they do not have the binaries for both architectures.
The following are the related assets in the lastest v10.2.0 release:
fd-v10.2.0-aarch64-apple-darwin.tar.gz
fd-v10.2.0-aarch64-unknown-linux-musl.tar.gz
fd-v10.2.0-x86_64-apple-darwin.tar.gz
fd-v10.2.0-x86_64-unknown-linux-musl.tar.gz
> feat: Add arm64/aarch64 support to fd package for v10.1.0+

- talosctl.hcl
I rebuilt this PR for #571 to go off of branches instead of main, much cleaner
> chore: add all the versions of talosctl (needed for use with multiple versions of talos)

- goss.hcl
Updates the goss package manifest to account for binary name changes in newer versions.
Older versions of goss used `alpha` in the name for non-linux based binaries. The newer versions of goss have dropped this naming difference.
Test digests
```
$ hermit manifest add-digests goss.hcl
info:goss: All packages have checksums!
```
Test packages
```
$ hermit test goss
info:validate: Validating goss-0.4.9
info:validate: Validating goss-0.3.21
info:validate: Validating goss-0.3.22
info:validate: Validating goss-0.3.23
info:validate: Validating goss@latest
info:validate: Validating goss@0
info:validate: Validating goss@0.3
info:validate: Validating goss@0.4
```
> fix: Support for newer goss versions

- gradle.hcl
Rather than GitHub releases which uses tags (eg. v8.13.0) that don't match the actual version (8.13).
> fix(gradle): use releases page for auto-versioning

- flux-build.hcl
Build and test kustomize overlays with flux2 HelmRelease support
> feat: add flux-build

- buildozer.hcl
Hermit support for [buildozer](https://github.com/bazelbuild/buildtools/tree/main/buildozer)
(related PR https://github.com/cashapp/hermit-packages/pull/599)
> feat: add support for buildozer

- vacuum.hcl
Vacuum is an open-api linter written in go.
> feat(vacuum): Adds initial package.

- gum.hcl
Since 0.14.0, `gum` has a leading directory in its artifacts; this causes errors like the following:
```
fatal:hermit: gum-0.14.5: failed to find binaries "/Users/wrenn/Library/Caches/hermit/pkg/gum-0.14.5/gum"
```
Strip this path component appropriately.
> fix(gum): strip path prefix for v0.14+

- python3.hcl
This adds the latest python3 version. The release page is here: https://www.python.org/downloads/release/python-3132/
> Add latest python3 version: 3.13.2

- dotslash.hcl
dotslash (https://dotslash-cli.com/) is a tool solving a problem
similar to Hermit. It is distributed as a single binary.
This adds dotslash to Hermit for use in repositories
that already have Hermit installed and need to also use dotslash.
> Add dotslash

- elixir.hcl
- erlang.hcl
Hermit support for [Elixir](https://elixir-lang.org/) and [Erlang](https://www.erlang.org/).
Erlang is required to run Elixir.
> Adds elixir and erlang

- ollama.hcl
Ollama updated their release process starting with 0.4.0, So I updated it to include 0.7.0 and all of the 0.6 releases.
> fix: upgrade ollama release source format

- jq.hcl
All existing releases were migrated to the new org.
> chore(jq): update urls to the new jqlang org

- fnm.hcl
`fnm` is a version manager for Node. It offers a flexible alternative to Hermit when one needs to manage multiple Node versions simultaneously in a Hermit project.
> feat: add fnm

- biome.hcl
```
hermit search biome
biome (@1, 1.6.4-nightly.a995ada, 1.6.4-nightly.abab451, 1.7.4-nightly.125f34b, @1.6, 1.8.4-nightly.7aaf0ce, 1.8.4-nightly.a579bf7, 1.8.4-nightly.bd1d0c6, 1.8.4-nightly.d079e53, 1.9.1-nightly.12688b6, 1.9.3-nightly.75b4387, 1.9.5-nightly.4713c52, 1.9.5-nightly.81fdedb, 1.9.5-nightly.92879ae, 1.9.5-nightly.c0cccb2, 1.9.5-nightly.ff02a0b, @1.7, @1.8, @1.9, @latest, 1.6.3, 1.6.4, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4)
A toolchain for web projects, aimed to provide functionalities to maintain them. Biome offers formatter and linter,
usable via CLI and LSP.
```
But biome has some `2.x.x` versions now : https://github.com/biomejs/biome/releases
> fix: biome autoversion for 2.x.x

- .gitignore
- python3.hcl
Process followed for future reference if someone needs to add another python version (thanks for your help 🪿 )
Goose did most of this for me automatically, but replaying the steps:
- Took a look at the most recent release we were referencing - https://github.com/astral-sh/python-build-standalone/releases/tag/20250317 (`indygreg` redirects to `astral-sh` now)
- Verified that it packages up `3.9.21`
- Added this version to right spot in `python3.hcl`
- Ran `hermit add-digests python3.hcl` to generate SHA digests.
- Ran `hermit test python3` to verify changes.
> feat: add python 3.9.21

- argc.hcl
Add [argc](https://github.com/sigoden/argc), a tool for easily building CLIs for Bash scripts.
> feat: add argc

- .github/workflows/ci.yml
If a PR is behind master, currently CI will result in testing all packages changed between the PR and origin/master. Hopefully this will fix that.
> fix: hopefully fix CI test overreach

- ibazel.hcl
Adding `ibazel`.
There is an [issue](https://github.com/bazelbuild/bazel-watcher/pull/776) with their github releases that means not every version has suitable binaries. I picked a recent-ish version that had at least `linux-amd64` `linux-arm64` and `darwin-arm64` available, but auto-versioning will not be possible for now.
> feat: add ibazel

- ibazel.hcl
The [release fix for ibazel](https://github.com/bazelbuild/bazel-watcher/pull/776) was released so we can add the latest version now.
Auto-versioning is still and issue with the mix of `v` and `V` prefixes on the release tags.
> feat: add latest version of ibazel

- uv.hcl
Adding the PYTHONUSERBASE env variable to uv the same as python3.hcl allowing better compatibility between existing python/pip and uv, allowing the one to use both pip and uv inter-changablity.
> uv: Add PYTHONUSERBASE env to uv

- .github/workflows/ci.yml
`hermit search -s <pkg>` will ignore manifest errors, deliberately, but as that was what was used to test new/updated packages, they would be completely skipped.
This PR changes the approach so that the package is always tested. It also skips the full set of version tests, because that slowly becomes more and more untenable as packages accrue versions.
> chore(ci): hopefully ensure that packages are tested if there are errors

- go-jsonschema.hcl
Adds [go-jsonschema ](https://github.com/omissis/go-jsonschema) - A tool to generate Go data types from JSON Schema definitions.
> Adds go-jsonschema

- rust.hcl
Auto version CI job was failing to update rust with this error: `fatal:hermit: rust.hcl: unknown variable $version`
I believe I was able to fix this, and also added two missing versions, 1.88.0 and 1.89.0.
> fix(rust): auto version 'unknown variable ' bug and updates versions

- rustup-init.hcl
- rustup.hcl
https://github.com/rust-lang/rustup doesn't use releases, only tags. This change ensures that new versions are correctly picked up.
> fix(rustup): use git-tags for auto-version for rustup repository

- hadolint.hcl
Starting in 2.13.1, hadolint includes arm64 builds and renamed darwin to "macos".
> fix: add arm64 for hadolint
