cashapp/hermit-packages

rust.hcl
rust/install.sh

Confirmed it can compile hello world.

Post-unpack Rust installation.

---

jx.hcl

for the Jenkins X project's command line interface: https://jenkins-x.io/

Adds the jx CLI

---

aws-iam-authenticator.hcl
awsu.hcl
cmake.hcl
elm.hcl
golangci-lint.hcl
goose.hcl
goreleaser.hcl
hugo.hcl
hyperfine.hcl
k3d.hcl
k9s.hcl
kotlin.hcl
ninja.hcl
protoc-gen-grpc-gateway-ts.hcl
protoc.hcl
rq.hcl
shellcheck.hcl
shfmt.hcl
sqlc.hcl
terragrunt.hcl
tilt.hcl
yq.hcl
zim.hcl

Also run `hermit manifest auto-version *.hcl`

auto-version everything currently possible.

---

kind.hcl

for running/testing kubernetes in docker:
see https://github.com/kubernetes-sigs/kind/

fix: add kind package

---

opa.hcl

Add `opa` to hermit packages.

---

packer.hcl

Adds a package for https://www.packer.io/

Adds a package for Hashicorp Packer

---

envoy.hcl

Ran across this, so figured I would update it if you like.
https://archive.tetratelabs.io/envoy/envoy-versions.json

Adds Envoy 1.19.0

---

gofumpt.hcl

Adds https://github.com/mvdan/gofumpt

Add gofumpt

---

skaffold.hcl

Add skaffold package from https://github.com/GoogleContainerTools/skaffold

Add skaffold package

---

prometheus.hcl

Add prometheus and promtool for local monitoring testing.
link: https://prometheus.io/
link: https://github.com/prometheus/prometheus/releases

Add prometheus and promtool

---

knative.hcl
kubectx.hcl
kubens.hcl

Add knative cli, kubectx and kubens

---

gotestsum.hcl

Gotestsum is a tool I often use for formatting go test runs and in CI pipelines.

Package for gotestsum

---

terraform.hcl

Add different versions of terraform including 0.11/0.12/0.13/0.14/0.15/1.0
and migrate to github release auto version

Add terraform versions

---

dive.hcl

Dive is a docker image analysis tool: https://github.com/wagoodman/dive

Add a package for dive

---

fd.hcl

This PR adds [fd](https://github.com/sharkdp/fd), a nice alternative to `find`.

Add fd package

---

tuist.hcl

tuist 2.7.2

---

adr-tools.hcl

Long time user, first time packager. Am I doing this right?

Package npryce/adr-tools

---

rome.hcl

Built in Rust - let's hope it delivers.
https://github.com/rome/tools

Add rome formatter

---

dagger.hcl

Verified with:
```console
$ hermit test dagger --trace --debug
info:validate: Validating dagger-0.2.6
trace: HEAD https://github.com/dagger/dagger/releases/download/v0.2.6/dagger_v0.2.6_linux_amd64.tar.gz
trace: HEAD https://objects.githubusercontent.com/github-production-release-asset-2e65be/222824662/5631eb3b-6498-4bc6-81e7-62e96fb03dbb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220414%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220414T125646Z&X-Amz-Expires=300&X-Amz-Signature=4d1b05825e6a7825635c5f30d9f22063b024b4bef863ea2260c37ddea72609b1&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=222824662&response-content-disposition=attachment%3B%20filename%3Ddagger_v0.2.6_linux_amd64.tar.gz&response-content-type=application%2Foctet-stream
trace: HEAD …
```

dagger: add initial manifest

---

secrets.hcl

A command-line tool to prevent committing secret keys into your source code.

Add secrets

---

gradle.hcl

Release notes: https://docs.gradle.org/7.4.2/release-notes.html

Add Gradle 7.4.2.

---

goproxy.hcl

add binaries and remove html tag in auto-version

fix goproxy errors from manifest create

---

migrate.hcl

Add entry for golang-migrate/migrate.

Add configuration for golang-migrate/migrate

---

awscli.hcl
azcopy.hcl
dart.hcl
envoy.hcl
flutter.hcl
go.hcl
gradle.hcl
k8s-lens.hcl
kubectl.hcl
maven.hcl
mysql-client.hcl
pixie.hcl
zig.hcl

Reverts cashapp/hermit-packages#154

Revert "fix: add repository for package that could not be inferred"

---

awscli.hcl
azcopy.hcl
dart.hcl
envoy.hcl
flutter.hcl
go.hcl
gradle.hcl
k8s-lens.hcl
kubectl.hcl
maven.hcl
mysql-client.hcl
pixie.hcl
zig.hcl

This PR's been previously merged but reverted as it is a breaking change to the manifest and will break the update. opening this again and to be merge next wk.

fix: add repository for package that could not be inferred

---

pulumi.hcl

Add Pulumi Manifest

---

prana-cli.hcl

Add PranaDB CLI binary to Hermit packages

Add PranaDB CLI

---

just.hcl

just 1.2.0

---

rustup-init.hcl

In lieu of getting proper rust support, let's get the bootstrap right!

Add rustup-init

---

confest.hcl

Adds https://github.com/open-policy-agent/conftest to be Hermit managed

Add Conftest

---

hcl2json.hcl

Adding `hcl2json` https://github.com/tmccombs/hcl2json to be Hermit managed

add hcl2json

---

firebase.hcl

See
* https://github.com/firebase/firebase-tools
* https://firebase.google.com/docs/web/setup

Add firebase CLI

---

terraform-docs.hcl

Updating `terraform-docs` to auto-version so we can stay up-to-date.

Terraform Docs Auto-Version

---

python3.hcl
python3/relocate.sh

Without this, any C modules will fail to compile.

fix: ensure python3 sysconfig paths are relocated

---

dotnet.hcl

the JQ parsing to get to a reasonable file format is not bad, but needed some python to format the json output in the expected hcl format

feat: add dotnet versions

---

konstraint.hcl

[Konstraint](https://github.com/plexsystems/konstraint) is a CLI tool to assist with the creation and management of templates and constraints when using [Gatekeeper](https://github.com/open-policy-agent/gatekeeper).

add Konstraint

---

mutagen.hcl

Add support for https://mutagen.io/

Add mutagen package

---

git-lfs.hcl

https://git-lfs.com/
https://github.com/git-lfs/git-lfs/releases

Add git-lfs package

---

crane.hcl

Add crane cli utility package 
https://github.com/google/go-containerregistry/blob/main/cmd/crane/README.md

add crane container tools cli

---

python3.hcl

Minor version bumps, and add support for Python 3.11!

Add new versions and Python 3.11

---

gradle.hcl

Hi team, 
I would like to use Gradle 8 RC with one of our projects. This PR makes it available to hermit.
Thank you.

Add Gradle 8 RC-2

---

codecov.hcl

Add codecov package

---

yamlfmt.hcl

See https://github.com/google/yamlfmt

Add yamlfmt

---

websocat.hcl

[websocat](https://github.com/vi/websocat#websocat) is a utility for interacting with websockets

Add websocat

---

gradle.hcl

https://docs.gradle.org/8.0.1/release-notes.html

Gradle 8.0.1

---

atlas.hcl

Resolves:
- https://github.com/cashapp/hermit/issues/287#issuecomment-1452723120
Relates to:
- https://github.com/ariga/atlas/issues/1498
- https://github.com/ariga/atlas/issues/1505

feat: atlas 'latest'

---

tfmigrate.hcl

Adding `tfmigrate` package to use with other Terraform tools managed by Hermit: https://github.com/minamijoyo/tfmigrate

Add tfmigrate Package

---

happy.hcl

happy 0.1.2

---

az-speechsdk.hcl

this is weird because it's not a binary, just a bunch of c library files, that language libraries link to themselves

feat: add azure speechsdk

---

happy.hcl

@alecthomas sorry mate – had to release again

happy 0.1.2 re-release

---

gradle.hcl

Checksum: https://gradle.org/release-checksums/#v8.1.1
Release Notes: https://docs.gradle.org/8.1.1/release-notes.html

chore: add gradle 8.1.1

---

azcopy.hcl

There's an Elon Musk joke in there somewhere with the release date ending with 420, but I won't go there :hand_over_mouth:

feat(azcopy.hcl): add version 10.18.1

---

node.hcl

https://github.com/nodejs/node/releases/tag/v20.0.0

node: v20 is the new current

---

devspace.hcl

This PR adds devspace package.
https://github.com/devspace-sh/devspace
https://devspace.sh

devspace package

---

sqlite.hcl

adds a year variable, unfortunately needs to be per-version.

chore: update sqlite

---

datadog-ci.hcl

WHY IS NOTHING FAILING TESTS 😭

datadog-ci: put the binary in the right place

---

openjdk.hcl

Apologies, I made an error on the sha. missing some commas.

Adds missing commas

---

dragonfly.hcl

https://github.com/dragonflydb/dragonfly
note: does not support macos. what is the right way to handle that? https://www.dragonflydb.io/docs/getting-started/binary#prerequisites

feat: add dragonflydb

---

gitleaks.hcl

[Gitleaks](https://github.com/gitleaks/gitleaks) is a cli to detect and protect against committing secrets into git repositories. I have tested this on my M1 MacBook Pro, but not on linux.

Add gitleaks cli

---

gradle.hcl

Release notes: https://docs.gradle.org/8.2/release-notes.html
Checksum: https://gradle.org/release-checksums/#v8.2

Add Gradle 8.2

---

op.hcl

I'd like to manage the 1Password CLI with Hermit, but I'm not sure how to get the Darwin pkg to work
```sh
hermit test op whoami
info:validate: Validating op-2.18.0
info:validate: Validating op@latest
fatal:hermit: op-2.18.0: failed to find binaries
```

add 1Password CLI

---

dart.hcl

Add dartsdk v3.0.5

---

bitwarden-cli.hcl

Adds the bitwarden password manager CLI.

feat: Add bitwarden CLI

---

gradle.hcl

Manually versioned: gradle.hcl

---

serverless.hcl

* Let's add the [Serverless framework](https://www.serverless.com/) binary installation.

Add serverless framework binary installation

---

node.hcl

- makes v20 LTS
- adds v21 as current
https://nodejs.org/en

Node.js v20 LTS

---

micromamba.hcl

added micromamba for conda environments

added micromamba

---

yj.hcl

Adds: https://github.com/sclevine/yj

feat: add yj for converting between JSON,YAML,TOML and HCL

---

micromamba.hcl

on hermit activate, run "micromamba activate"

auto activate micromamba

---

ffmpeg.hcl

Handle change in release artifact filename for ffmpeg

---

gradle.hcl

Release Notes: https://docs.gradle.org/8.6/release-notes.html
Checksum: https://gradle.org/release-checksums/#v8.6

Add Gradle 8.6

---

dprint.hcl

https://github.com/dprint/dprint

feat: add dprint

---

argocd.hcl

PR Adds ArgoCD CLI
https://github.com/argoproj/argo-cd

ArgoCD CLI

---

python3.hcl

This reverts commit 15f386034096e9b934f2cc8d4b652f37462252a5.

Revert "Add Python 3.12.2"

---

python3.hcl
python3/relocate.sh

The new version includes a link to "python", which was previously done by the manifest, so this PR also switches to conditionally installing it.

Add latest Python3

---

go.hcl

* `v1.22.1` https://github.com/golang/go/issues?q=milestone%3AGo1.22.1+label%3ACherryPickApproved
* `v1.21.8` https://github.com/golang/go/issues?q=milestone%3AGo1.21.8+label%3ACherryPickApproved+
* `v1.21.7` https://github.com/golang/go/issues?q=milestone%3AGo1.21.7+label%3ACherryPickApproved+

build(golang): added v1.22.1, v1.21.7, v1.21.8

---

jira-cli.hcl

https://github.com/ankitpokhrel/jira-cli
Tested on `macOS` `14.3`

Add jira-cli

---

gradle.hcl

Hello, I am currently seeking to add gradle 8.0.2 since some projects that are using hermit have updated to gradle 8.0.2 :)

Adds gradle 8.0.2

---

gradle.hcl

Release Notes: https://docs.gradle.org/8.7/release-notes.html
Checksum: https://gradle.org/release-checksums/#v8.7

Add Gradle 8.7

---

docker-cli.hcl

Hey Alec,
This PR add docker CLI for darwin and linux starting from 20.10.
Best,
Dominik

Docker CLI

---

google-java-format.hcl
google-java-format/google-java-format.sh

Copied the same structure as `ktfmt`

Add google-java-format

---

kyverno-cli.hcl

Initializing configuration for the Kyverno CLI: https://kyverno.io/docs/kyverno-cli/

feat: init kyverno-cli

---

aws-sam-cli.hcl

* new aws-sam-cli package
* tested on arm64 mac

added aws-sam-cli package

---

chainsaw.hcl

Adding https://github.com/kyverno/chainsaw

feat: add kyverno/chainsaw manifest

---

trivy.hcl

This PR adds Trivy from https://github.com/aquasecurity/trivy

trivy vulnerability and config scanner

---

protoc-gen-go-vtproto.hcl

Theres a couple of newer releases here

add latest vtproto versions

---

gradle.hcl

Release Notes: https://docs.gradle.org/8.9/release-notes.html
Checksum: https://gradle.org/release-checksums/#v8.9

Add Gradle 8.9

---

vendir.hcl

This PR adds vendir from https://github.com/carvel-dev/vendir

Adds vendir

---

flutter.hcl

Update flutter.hcl 3.22.3

---

flutter.hcl

Adding Flutter 3.24 to hermit @alecthomas

Update flutter.hcl 3.24.0

---

flutter.hcl

In the previous PR https://github.com/cashapp/hermit-packages/pull/509 the formatting was wrong. @alecthomas

fix incorrect format in flutter.hcl file

---

gradle.hcl

Release notes: https://docs.gradle.org/8.10/release-notes.html
Checksums: https://gradle.org/release-checksums/#v8.10

Add Gradle 8.10

---

tfenv.hcl

Added the Terraform Version Manager: [tfenv](https://github.com/tfutils/tfenv)

feat(tools): Added tfenv package

---

tf-summarize.hcl

Package for https://github.com/dineshba/tf-summarize

tf-summarize

---

xh.hcl

feat: add xh

---

ftl.hcl

Adds `ftl-language-go`, `ftl-language-java` and`ftl-language-kotlin` binaries.

update FTL binaries patterns

---

gradle.hcl

Release notes: https://docs.gradle.org/8.11/release-notes.html
Checksums: https://gradle.org/release-checksums/#8.11

Gradle 8.11

---

sonar-scanner-cli.hcl

Validated with an enterprise SonarQube instance in CI.

feat: add sonar-scanner-cli

---

bktec.hcl

Adds https://github.com/buildkite/test-engine-client

Add buildkite bktec

---

pact-go.hcl

Adds a package for https://github.com/pact-foundation/pact-go

Add pact-go

---

tailwindcss.hcl

https://tailwindcss.com/blog/standalone-cli

feat: add tailwindcss CLI

---

config-file-validator.hcl

https://github.com/Boeing/config-file-validator

feat: add config-file-validator 

---

myks.hcl

Myks is currently not supported yet.

Add Myks Cli

---

civo.hcl

Add CiVo Cli

---

kotlin-format.hcl
kotlin-format/kotlin-format.sh

Following how ktfmt is set up https://github.com/cashapp/hermit-packages/pull/219

Add kotlin-format

---

stern.hcl

Package for https://github.com/stern/stern

feat: stern package

---

dart.hcl

add dart 3.6.0

---

kubectl-neat.hcl

Adding `kubectl-neat` (https://github.com/itaysk/kubectl-neat) as an installable package

feat(kubectl-neat): init package

---

dgctl.hcl

This pull request includes significant updates to the `dgctl.hcl` file, focusing on adding a description, repository details, test command, binaries, source URL, unpacking instructions, versioning information, and SHA256 checksums for various releases.
Key changes include:
* Added metadata:
* Description of the `dgctl` tool.
* Repository URL for the source code.
* Test command to verify the installation.
* List of binaries included.
* Source URL template for downloading binaries.
* Added unpacking instructions to rename the binary after download.
* Added versioning information for versions `0.6.85` and `0.6.86` with auto-versioning based on GitHub releases.
* Added SHA256 checksums for the binaries corresponding to the specified versions and platforms.

feat: add dgctl

---

ftzz.hcl

ftzz is a fuzzing tool to create a pseudo-random file tree hierarchy.

feat: add ftzz

---

gradle.hcl

Release Notes: https://docs.gradle.org/8.13/release-notes.html
Checksum: https://gradle.org/release-checksums/#v8.13

Add Gradle 8.13

---

gradle-profiler.hcl

Contains fixes for latest stable Android Studio versions

Add Gradle Profiler 0.22.0-alpha-1

---

mysql-client.hcl
mysqladmin.hcl

Follow up to https://github.com/cashapp/hermit-build/pull/30

feat: add digest for mysql 8.0.40 + arm64 (percona)

---

depot.hcl

feat: add depot.dev cli tool

---

buildifier.hcl

Hermit support for [buildifier](https://github.com/bazelbuild/buildtools/blob/main/buildifier/README.md)

feat: add buildifier 

---

argo.hcl

This is my first hermit package, so it's entirely likely I fouled it up.

feat: add argo

---

bazelisk.hcl

Source: https://github.com/bazelbuild/bazelisk
Compare to: https://github.com/Homebrew/homebrew-core/blob/master/Formula/b/bazelisk.rb

feat: Add package definition for `bazelisk`

---

flux-operator.hcl

Flux Operator is a Kubernetes controller for managing the lifecycle of Flux CD.
https://github.com/controlplaneio-fluxcd/flux-operator

feat: flux-operator

---

opengrep.hcl

This PR onboards OpenGrep as an available package for Hermit
- [Relevant OpenGrep Release](https://github.com/opengrep/opengrep/releases)

feat: Add OpenGrep Package

---

vector.hcl

Vector has a collection of validation tools for use in ci (`vector validate`).

feat: add vector

---

jsonschema.hcl

Added: https://github.com/sourcemeta/jsonschema

feat: added jsonschema

---

controller-gen.hcl

Adds controller-gen from kubernetes controller-tools
Github: https://github.com/kubernetes-sigs/controller-tools

kubernetes controller-gen

---

setup-envtest.hcl

Adds setup-envtest from kubernetes controller-runtime testing
Github: https://github.com/kubernetes-sigs/controller-runtime

kubernetes setup-envtest

---

git-chglog.hcl

CHANGELOG generator implemented in Go (Golang).

feat: add git-chglog

---

rv.hcl

feat: Add a package definition for `rv`

---

AGENTS.md

This is the AGENTS.md I've been using for some months, really helps with package creation.

chore: Add AGENTS.md

---

nushell.hcl

More info at the Nushell site: https://www.nushell.sh/

Add nushell.hcl
